spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=interclassApp
server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


api.security.token.secret=${JWT_SECRET_FUTSUMULA:H1ghT3ch-4r3n4-S3cur1ty-K3y-2026!}
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dt67rf1r0}
cloudinary.api_key=${CLOUDINARY_API_KEY:769278297997512}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:lw79I8urGco0TiuNlWJqexPtcTo}

spring.main.allow-bean-definition-overriding=true