spring.datasource.url=jdbc:postgresql://localhost:5432/intercalsseApp_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.application.name=interclassApp
server.port=8015

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# \uD83D\uDD25 CONFIGURAÇÃO BLINDADA COM VALORES DE BACKUP PARA RODAR LOCALMENTE \uD83D\uDD25
api.security.token.secret=${JWT_SECRET_FUTSUMULA:H1ghT3ch-4r3n4-S3cur1ty-K3y-2026!}
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dt67rf1r0}
cloudinary.api_key=${CLOUDINARY_API_KEY:769278297997512}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:lw79I8urGco0TiuNlWJqexPtcTo}

spring.main.allow-bean-definition-overriding=true