
spring.datasource.url=jdbc:postgresql://localhost:5432/intercalsseApp_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.application.name=interclassApp
server.port=8015

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


cloudinary.cloud_name=dt67rf1r0
cloudinary.api_key=769278297997512
cloudinary.api_secret=lw79I8urGco0TiuNlWJqexPtcTo


spring.main.allow-bean-definition-overriding=true